version: '2'

services:
  mongo:
    image: mongo:4.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/PeopleDB
    container_name: people_mongo

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
    - 8081:8081
    container_name: people_mongo_express
    depends_on:
    - mongo